"""
Django settings for uap_cse_dj project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Load environment variables from .env file (for local development)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%17$(jt2p_eq*!i%3zr&ey_=f#an5a_2w8i=9$e!u8o!q7wc9p'

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to False in production (when DATABASE_URL is set, we're on Railway)
DEBUG = not bool(os.getenv('DATABASE_URL'))  # False in production (Railway), True in local development

ALLOWED_HOSTS = [
    'uapcsedj-production.up.railway.app', 
    '127.0.0.1', 
    'localhost',
    '.railway.app' # This wildcard allows any railway subdomain
]

# CSRF trusted origins for HTTPS requests
CSRF_TRUSTED_ORIGINS = [
    'https://uapcsedj-production.up.railway.app',
    'https://*.railway.app',  # Allow any railway subdomain
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'easy_thumbnails',
    'image_cropping',
    'designs',
    'people',
    'academics',
    'office',
    'clubs',
]

# Custom User Model
AUTH_USER_MODEL = 'people.BaseUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Trust proxy headers (needed for Railway/Heroku/etc)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'uap_cse_dj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'designs.context_processors.admission_elements',
                'office.context_processors.uap_now_posts',
                'clubs.context_processors.clubs',
            ],
        },
    },
]

WSGI_APPLICATION = 'uap_cse_dj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use PostgreSQL if DATABASE_URL is set (Railway production), otherwise use SQLite (local development)
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Parse DATABASE_URL and configure PostgreSQL
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Default to SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Directory where collectstatic will gather all static files

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads)
# In production (Railway), media files are stored in a mounted volume at /app/media
# In local development, media files are stored in the local media/ directory
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor settings
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
    },
}

# Easy Thumbnails settings
THUMBNAIL_ALIASES = {
    '': {
        '1:1': {'size': (400, 400), 'crop': 'smart'},
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings (for password reset)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mdsahriar.asif@gmail.com'
EMAIL_HOST_PASSWORD = 'mhkz utxt afnr wute'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Media file size limits and compression settings
# Size limits in KB (for images) and MB (for PDFs)
MEDIA_SIZE_LIMITS = {
    # Profile pictures (300KB threshold)
    'profile_pictures': {
        'max_size_kb': 300,
        'target_dimensions': (400, 400),
        'quality': 85,
    },
    # Club logos (200KB threshold)
    'club_logos': {
        'max_size_kb': 200,
        'target_dimensions': (400, 400),
        'quality': 90,
    },
    # Club cover photos (500KB threshold)
    'club_covers': {
        'max_size_kb': 500,
        'target_dimensions': (2100, 600),
        'quality': 85,
    },
    # Feature cards (500KB threshold)
    'feature_cards': {
        'max_size_kb': 500,
        'target_dimensions': (400, 400),
        'quality': 85,
    },
    # Class routines (1MB threshold)
    'class_routines': {
        'max_size_kb': 1000,
        'max_width': 2000,
        'quality': 80,
    },
}

# PDF file size limits in MB
PDF_SIZE_LIMITS = {
    'faculty_cv': 5,  # MB
    'curriculum_pdf': 10,  # MB
    'academic_calendar': 5,  # MB
    'admission_result': 10,  # MB
    'post_attachment': 10,  # MB
    'course_outline': 5,  # MB
}
