# Generated by Django 5.2 on 2025-12-10 00:22

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True, help_text='Records when the notice was issued', verbose_name='Publish Date/Time')),
                ('short_title', models.CharField(help_text='Concise, max 20 characters for display (max 4 words)', max_length=20, verbose_name='Short Title')),
                ('long_title', models.CharField(help_text='Detailed headline for the announcement', max_length=255, verbose_name='Long Title')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'urgent, closure')", max_length=200, null=True, verbose_name='Tags')),
                ('description', ckeditor.fields.RichTextField(help_text='Full body of the announcement', verbose_name='Description')),
                ('created_by', models.ForeignKey(help_text='Links to the existing authorized user who created the notice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='NoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='File attachment for the notice', upload_to='notices/attachments/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded', verbose_name='Uploaded At')),
                ('notice', models.ForeignKey(help_text='Link to the parent notice', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='office.notice', verbose_name='Notice')),
            ],
            options={
                'verbose_name': 'Notice Attachment',
                'verbose_name_plural': 'Notice Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True, help_text='Records when the result was posted', verbose_name='Publish Date/Time')),
                ('academic_year', models.SmallIntegerField(help_text='Numerical year (e.g., 2026)', verbose_name='Academic Year')),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], help_text='Fixed choices: Fall or Spring', max_length=10, verbose_name='Semester')),
                ('slot', models.IntegerField(help_text='The specific admission slot (e.g., 1, 2, 3)', verbose_name='Slot')),
                ('result_content', ckeditor.fields.RichTextField(help_text='Main body displayed on the webpage', verbose_name='Result Content')),
                ('official_pdf', models.FileField(help_text='Single file for the official, signed result document', upload_to='admission_results/', verbose_name='Official PDF')),
                ('created_by', models.ForeignKey(help_text='Links to the existing authorized user who created the post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admission_results', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Admission Result',
                'verbose_name_plural': 'Admission Results',
                'ordering': ['-publish_date', '-academic_year', 'semester', 'slot'],
                'unique_together': {('academic_year', 'semester', 'slot')},
            },
        ),
    ]
