# Generated by Django 5.2 on 2025-12-10 00:26

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeattachment',
            name='notice',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True, help_text='Records when the post was issued', verbose_name='Publish Date/Time')),
                ('post_type', models.CharField(choices=[('notice', 'Notice'), ('events', 'Events'), ('seminars', 'Seminars'), ('workshop', 'Workshop'), ('others', 'Others')], default='notice', help_text='Category of the post: notice, events, seminars, workshop, or others', max_length=20, verbose_name='Post Type')),
                ('short_title', models.CharField(help_text='Concise, max 20 characters for display (max 4 words)', max_length=20, verbose_name='Short Title')),
                ('long_title', models.CharField(help_text='Detailed headline for the announcement', max_length=255, verbose_name='Long Title')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'urgent, closure')", max_length=200, null=True, verbose_name='Tags')),
                ('description', ckeditor.fields.RichTextField(help_text='Full body of the announcement', verbose_name='Description')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this post to the top of the list', verbose_name='Pin Post')),
                ('created_by', models.ForeignKey(help_text='Links to the existing authorized user who created the post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-is_pinned', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='File attachment for the post', upload_to='posts/attachments/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded', verbose_name='Uploaded At')),
                ('post', models.ForeignKey(help_text='Link to the parent post', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='office.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post Attachment',
                'verbose_name_plural': 'Post Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='NoticeAttachment',
        ),
    ]
