# Generated by Django 5.2 on 2025-12-10 00:26

from django.db import migrations
from django.utils import timezone
from datetime import timedelta
import random


def create_sample_posts(apps, schema_editor):
    """
    Create 110+ sample posts with different types, dates (past and future), and content.
    """
    Post = apps.get_model('office', 'Post')
    BaseUser = apps.get_model('people', 'BaseUser')
    
    # Get or create a user for created_by (use first user with level >= 3, or create a dummy one)
    user = BaseUser.objects.filter(access_level__in=['3', '4', '5']).first()
    if not user:
        # Create a dummy user if none exists
        user = BaseUser.objects.create_user(
            username='admin_post',
            email='admin@uap-bd.edu',
            password='dummy',
            user_type='officer',
            access_level='3',
            first_name='Admin',
            last_name='User'
        )
    
    # Post type choices
    post_types = ['notice', 'events', 'seminars', 'workshop', 'others']
    
    # Sample data for different post types
    notice_titles = [
        ('Exam Schedule', 'Final Examination Schedule for Spring 2025 Semester'),
        ('Holiday Notice', 'University Holiday Notice - Eid-ul-Fitr Celebration'),
        ('Fee Payment', 'Tuition Fee Payment Deadline Extended'),
        ('Library Hours', 'Library Extended Hours During Exam Period'),
        ('Parking Rules', 'New Parking Rules and Regulations Effective'),
        ('ID Card', 'Student ID Card Renewal Process'),
        ('Graduation', 'Graduation Ceremony 2025 Announcement'),
        ('Scholarship', 'Merit Scholarship Application Open'),
        ('Lab Access', 'Computer Lab Access Rules Updated'),
        ('WiFi Access', 'Campus WiFi Password Reset'),
    ]
    
    events_titles = [
        ('Tech Fest', 'Annual Technology Festival 2025'),
        ('Hackathon', 'Inter-University Hackathon Competition'),
        ('Career Fair', 'Career Fair and Job Placement Event'),
        ('Cultural Day', 'Cultural Day Celebration and Performances'),
        ('Sports Meet', 'Annual Sports Meet and Competition'),
        ('Alumni Meet', 'Alumni Reunion and Networking Event'),
        ('Startup Pitch', 'Startup Pitch Competition Finals'),
        ('Robotics Show', 'Robotics Exhibition and Competition'),
        ('Code Contest', 'Programming Contest and Coding Challenge'),
        ('Project Expo', 'Final Year Project Exhibition'),
    ]
    
    seminars_titles = [
        ('AI Seminar', 'Artificial Intelligence and Machine Learning Seminar'),
        ('Blockchain Talk', 'Blockchain Technology and Cryptocurrency Discussion'),
        ('Cloud Computing', 'Cloud Computing and DevOps Best Practices'),
        ('Cybersecurity', 'Cybersecurity Threats and Prevention Strategies'),
        ('Data Science', 'Data Science and Big Data Analytics Workshop'),
        ('IoT Workshop', 'Internet of Things and Smart Devices'),
        ('Web Dev', 'Modern Web Development Frameworks'),
        ('Mobile App', 'Mobile Application Development Trends'),
        ('Game Dev', 'Game Development and Design Principles'),
        ('Quantum Computing', 'Quantum Computing and Future Technologies'),
    ]
    
    workshop_titles = [
        ('Python Basics', 'Python Programming Workshop for Beginners'),
        ('Django Framework', 'Django Web Framework Development Workshop'),
        ('React JS', 'React.js Frontend Development Workshop'),
        ('Node.js', 'Node.js Backend Development Workshop'),
        ('Database Design', 'Database Design and SQL Workshop'),
        ('Git Version', 'Git and Version Control Workshop'),
        ('Docker Basics', 'Docker Containerization Workshop'),
        ('AWS Cloud', 'Amazon Web Services Cloud Computing Workshop'),
        ('UI/UX Design', 'User Interface and User Experience Design Workshop'),
        ('Mobile Dev', 'Mobile App Development Workshop'),
    ]
    
    others_titles = [
        ('Research Opp', 'Research Opportunities for Undergraduate Students'),
        ('Internship Info', 'Summer Internship Program Information'),
        ('Study Abroad', 'Study Abroad Program Applications Open'),
        ('Research Grant', 'Research Grant Application Deadline'),
        ('Conference Call', 'Call for Papers - International Conference'),
        ('Journal Pub', 'Journal Publication Guidelines and Support'),
        ('Mentorship', 'Student Mentorship Program Launch'),
        ('Peer Tutoring', 'Peer Tutoring Program Registration'),
        ('Study Group', 'Study Group Formation and Guidelines'),
        ('Resource Center', 'New Learning Resource Center Opening'),
    ]
    
    # Combine all titles
    all_titles = {
        'notice': notice_titles,
        'events': events_titles,
        'seminars': seminars_titles,
        'workshop': workshop_titles,
        'others': others_titles,
    }
    
    # Tags pool
    tags_pool = [
        'urgent', 'important', 'academic', 'administrative', 'student',
        'faculty', 'research', 'technology', 'innovation', 'career',
        'development', 'learning', 'competition', 'networking', 'opportunity',
        'deadline', 'registration', 'application', 'scholarship', 'event'
    ]
    
    # Generate posts
    posts_created = 0
    now = timezone.now()
    
    # Create posts with dates spread across past 2 years and future 1 year
    for i in range(115):  # Create 115 posts
        # Distribute dates: 60% past, 40% future
        if i < 69:  # Past posts (60%)
            days_offset = random.randint(-730, -1)  # Past 2 years
        else:  # Future posts (40%)
            days_offset = random.randint(1, 365)  # Next year
        
        publish_date = now + timedelta(days=days_offset)
        
        # Add random hours and minutes for variety
        hours_offset = random.randint(0, 23)
        minutes_offset = random.randint(0, 59)
        publish_date = publish_date.replace(hour=hours_offset, minute=minutes_offset)
        
        # Select post type (weighted distribution)
        if i < 30:
            post_type = 'notice'
        elif i < 50:
            post_type = 'events'
        elif i < 75:
            post_type = 'seminars'
        elif i < 95:
            post_type = 'workshop'
        else:
            post_type = 'others'
        
        # Get titles for this post type
        type_titles = all_titles[post_type]
        short_title, long_title = random.choice(type_titles)
        
        # Generate tags (1-4 random tags)
        num_tags = random.randint(1, 4)
        selected_tags = random.sample(tags_pool, num_tags)
        tags = ', '.join(selected_tags)
        
        # Generate description
        description = f"""
        <p>This is a detailed description for the post: <strong>{long_title}</strong>.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>For more information, please contact the administration office or visit our website.</p>
        """
        
        # Pin some posts (about 10% of posts)
        is_pinned = random.random() < 0.1
        
        # Create the post
        post = Post.objects.create(
            publish_date=publish_date,
            post_type=post_type,
            short_title=short_title,
            long_title=long_title,
            tags=tags,
            description=description,
            is_pinned=is_pinned,
            created_by=user
        )
        posts_created += 1
    
    print(f"Created {posts_created} sample posts")


def remove_sample_posts(apps, schema_editor):
    """
    Remove all sample posts created by this migration.
    """
    Post = apps.get_model('office', 'Post')
    Post.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_remove_noticeattachment_notice_post_postattachment_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_posts, remove_sample_posts),
    ]
