# Generated by Django 5.2 on 2025-12-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_classroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='Email of the user who created this result (preserved even if user is deleted)', max_length=254, null=True, verbose_name='Created By Email'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='created_by_name',
            field=models.CharField(blank=True, help_text='Name of the user who created this result (preserved even if user is deleted)', max_length=255, null=True, verbose_name='Created By Name'),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='Email of the user who created this routine (preserved even if user is deleted)', max_length=254, null=True, verbose_name='Created By Email'),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='created_by_name',
            field=models.CharField(blank=True, help_text='Name of the user who created this routine (preserved even if user is deleted)', max_length=255, null=True, verbose_name='Created By Name'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text='Email of the user who created this post (preserved even if user is deleted)', max_length=254, null=True, verbose_name='Created By Email'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_by_name',
            field=models.CharField(blank=True, help_text='Name of the user who created this post (preserved even if user is deleted)', max_length=255, null=True, verbose_name='Created By Name'),
        ),
    ]
