# Generated by Django 5.2 on 2025-12-13 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('office', '0005_admissionresult_created_by_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_text', models.TextField(help_text='Full text content extracted from the document')),
                ('embedding', models.JSONField(help_text='384-dimensional vector embedding (from sentence-transformers/all-MiniLM-L6-v2)')),
                ('metadata', models.JSONField(default=dict, help_text='Stores title, date, type, and other metadata for quick access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Document Embedding',
                'verbose_name_plural': 'Document Embeddings',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='office_docu_content_e05a61_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
