# Generated by Django 5.2 on 2025-12-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_documentembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='embedding',
            field=models.JSONField(blank=True, help_text='384-dimensional vector embedding (from sentence-transformers/all-MiniLM-L6-v2)', null=True),
        ),
    ]
