# Generated by Django 5.2 on 2025-12-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_alter_documentembedding_embedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentEmbedding',
        ),
    ]
