# Generated by Django 6.0 on 2025-12-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_delete_documentembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionresult',
            name='official_pdf',
            field=models.FileField(help_text='Single file for the official, signed result document (Max 10MB)', upload_to='admission_results/', verbose_name='Official PDF'),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='routine_image',
            field=models.ImageField(help_text='The timetable image (Max 1MB, will be compressed and resized to max width 2000px if larger)', upload_to='class_routines/', verbose_name='Routine Image'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(help_text='File attachment for the post (PDF only, Max 10MB)', upload_to='posts/attachments/', verbose_name='File'),
        ),
    ]
