# Generated by Django 6.0 on 2025-12-29 09:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_alter_admissionresult_official_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(help_text='The year (e.g., 2025)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)], verbose_name='Academic Year')),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], help_text='The academic period: Fall or Spring', max_length=10, verbose_name='Semester')),
                ('type_of_exam', models.CharField(choices=[('mid', 'Mid'), ('final', 'Final')], help_text='Mid or Final exam', max_length=10, verbose_name='Type of Exam')),
                ('year_semester', models.CharField(choices=[('1-1', 'Year 1, Semester 1'), ('1-2', 'Year 1, Semester 2'), ('2-1', 'Year 2, Semester 1'), ('2-2', 'Year 2, Semester 2'), ('3-1', 'Year 3, Semester 1'), ('3-2', 'Year 3, Semester 2'), ('4-1', 'Year 4, Semester 1'), ('4-2', 'Year 4, Semester 2')], help_text='Student level (e.g., 1-1, 2-2, 4-2)', max_length=3, verbose_name='Year-Semester')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text='Class division (A to E)', max_length=1, verbose_name='Section')),
                ('routine_image', models.ImageField(help_text='The exam timetable image (Max 1MB, will be compressed and resized to max width 2000px if larger)', upload_to='exam_routines/', verbose_name='Routine Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the routine was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the routine was last updated', verbose_name='Updated At')),
                ('created_by_name', models.CharField(blank=True, help_text='Name of the user who created this routine (preserved even if user is deleted)', max_length=255, null=True, verbose_name='Created By Name')),
                ('created_by_email', models.EmailField(blank=True, help_text='Email of the user who created this routine (preserved even if user is deleted)', max_length=254, null=True, verbose_name='Created By Email')),
                ('created_by', models.ForeignKey(help_text='Links to the user who created the routine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_routines', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Exam Routine',
                'verbose_name_plural': 'Exam Routines',
                'ordering': ['-academic_year', 'semester', 'type_of_exam', 'year_semester', 'section'],
                'unique_together': {('academic_year', 'semester', 'type_of_exam', 'year_semester', 'section')},
            },
        ),
    ]
