# Generated by Django 6.0 on 2025-12-29 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_examroutine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.PositiveIntegerField(help_text='Controls the display order (lower numbers appear first).', verbose_name='Serial Number (SL)')),
                ('short_title', models.CharField(help_text="Concise title for the image (e.g., 'Orientation 2025').", max_length=100, verbose_name='Short Title')),
                ('description', models.CharField(blank=True, help_text='Optional short caption/description (not too big).', max_length=255, null=True, verbose_name='Short Description')),
                ('image', models.ImageField(help_text='Gallery image (will be stored under media/gallery/).', upload_to='gallery/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this gallery item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this gallery item was last updated.', verbose_name='Updated At')),
                ('created_by_name', models.CharField(blank=True, help_text='Name of the user who created this item (preserved even if user is deleted).', max_length=255, null=True, verbose_name='Created By Name')),
                ('created_by_email', models.EmailField(blank=True, help_text='Email of the user who created this item (preserved even if user is deleted).', max_length=254, null=True, verbose_name='Created By Email')),
                ('created_by', models.ForeignKey(blank=True, help_text='Power user who created this gallery item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gallery_items', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['sl', '-created_at'],
                'unique_together': {('sl', 'short_title')},
            },
        ),
    ]
