# Generated by Django 6.0 on 2025-12-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='featured',
            field=models.BooleanField(default=False, help_text='If checked, this image will appear in the homepage highlight gallery.', verbose_name='Show on Home Page'),
        ),
    ]
