# Generated by Django 6.0 on 2026-01-04 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_gallery_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='academic_year',
            field=models.IntegerField(help_text='The year (e.g., 2025)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2031)], verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='academic_year',
            field=models.IntegerField(help_text='The year (e.g., 2025)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2031)], verbose_name='Academic Year'),
        ),
    ]
