# Generated by Django 5.2 on 2026-01-07 17:49

import office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_alter_classroutine_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image (max 1 MB, any aspect ratio)', null=True, upload_to='posts/thumbnails/', validators=[office.models.validate_thumbnail_size], verbose_name='Thumbnail Image'),
        ),
    ]
