# Generated by Django 5.2 on 2025-12-11 18:43

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0015_alter_faculty_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official, unique name of the club', max_length=100, unique=True)),
                ('sl', models.PositiveIntegerField(blank=True, help_text='Serial number for ordering', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('moto', models.CharField(blank=True, help_text="The club's motto or slogan", max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text="Detailed information about the club's goals and activities", null=True)),
                ('logo', image_cropping.fields.ImageCropField(blank=True, help_text='Small club logo', null=True, upload_to='club_assets/logos/')),
                ('logo_cropping', image_cropping.fields.ImageRatioField('logo', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop to 1:1 aspect ratio', hide_image_field=False, size_warning=True, verbose_name='logo cropping')),
                ('cover_photo', image_cropping.fields.ImageCropField(blank=True, help_text="Large banner image for the club's profile", null=True, upload_to='club_assets/covers/')),
                ('cover_photo_cropping', image_cropping.fields.ImageRatioField('cover_photo', '2100x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop to the 21:6 aspect ratio', hide_image_field=False, size_warning=True, verbose_name='cover photo cropping')),
                ('website_url', models.URLField(blank=True, help_text='Official club website URL', max_length=255, null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', max_length=255, null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', max_length=255, null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convener', models.ForeignKey(blank=True, help_text='The faculty member advising the club (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convened_clubs', to='people.faculty')),
                ('president', models.ForeignKey(blank=True, help_text='The club member designated as the current President (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_clubs', to='people.clubmember')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['sl', 'name'],
            },
        ),
    ]
