# Generated by Django 5.2 on 2025-12-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name or abbreviation for the club', max_length=50, null=True),
        ),
    ]
