# Generated by Django 5.2 on 2025-12-11 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_short_name'),
        ('people', '0015_alter_faculty_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(help_text='Title of the position (e.g., Vice President, Secretary, Treasurer)', max_length=100)),
                ('academic_year', models.SmallIntegerField(help_text='Academic year (e.g., 2024)', validators=[django.core.validators.MinValueValidator(2000)])),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], help_text='Semester: Fall or Spring', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(help_text='The club this position belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='clubs.club')),
                ('club_member', models.ForeignKey(blank=True, help_text='Club member in this position (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_positions', to='people.clubmember')),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty member in this position (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_positions', to='people.faculty')),
            ],
            options={
                'verbose_name': 'Club Position',
                'verbose_name_plural': 'Club Positions',
                'ordering': ['-academic_year', 'semester', 'position_title'],
                'unique_together': {('club', 'position_title', 'academic_year', 'semester', 'club_member'), ('club', 'position_title', 'academic_year', 'semester', 'faculty')},
            },
        ),
    ]
