# Generated by Django 5.2 on 2025-12-11 19:50

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the post', max_length=255)),
                ('content', ckeditor.fields.RichTextField(help_text='Post content with rich text formatting')),
                ('publish_date', models.DateTimeField(auto_now_add=True, help_text='When the post was published')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the post was last updated')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this post to the top')),
                ('club', models.ForeignKey(help_text='The club this post belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='clubs.club')),
                ('created_by', models.ForeignKey(help_text='User who created this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_club_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club Post',
                'verbose_name_plural': 'Club Posts',
                'ordering': ['-is_pinned', '-publish_date'],
            },
        ),
    ]
