# Generated by Django 5.2 on 2025-12-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_clubpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubposition',
            options={'ordering': ['-academic_year', 'semester', 'sl', 'position_title'], 'verbose_name': 'Club Position', 'verbose_name_plural': 'Club Positions'},
        ),
        migrations.AddField(
            model_name='clubposition',
            name='sl',
            field=models.PositiveIntegerField(default=1, help_text='Serial number for ordering within the club (used for sorting, not displayed)'),
        ),
    ]
