# Generated by Django 5.2 on 2025-12-11 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_update_clubpost_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpost',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin this post to the top (max 3 per club)'),
        ),
        migrations.AlterField(
            model_name='clubpost',
            name='posted_by',
            field=models.ForeignKey(help_text='The original user who created this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_club_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
