# Generated by Django 5.2 on 2025-12-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_add_description_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpost',
            name='posted_by_email',
            field=models.EmailField(blank=True, help_text='Email of the user who posted this (preserved even if user is deleted)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clubpost',
            name='posted_by_name',
            field=models.CharField(blank=True, help_text='Name of the user who posted this (preserved even if user is deleted)', max_length=255, null=True),
        ),
    ]
