# Generated by Django 6.0 on 2025-12-24 22:03

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_clubpost_posted_by_email_clubpost_posted_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='cover_photo',
            field=image_cropping.fields.ImageCropField(blank=True, help_text="Large banner image for the club's profile (Max 500KB, will be compressed and resized to 2100x600px if larger)", null=True, upload_to='club_assets/covers/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='Small club logo (Max 200KB, will be compressed and resized to 400x400px if larger)', null=True, upload_to='club_assets/logos/'),
        ),
    ]
