# Generated by Django 5.2 on 2025-12-08 16:21

import ckeditor.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('faculty', 'Faculty'), ('staff', 'Staff'), ('officer', 'Officer'), ('club_member', 'Club Member')], help_text='Type of user (synced from AllowedEmail)', max_length=20)),
                ('access_level', models.CharField(choices=[('5', 'Head'), ('4', 'Super Admin'), ('3', 'Course Access'), ('2', 'General User'), ('1', 'Club Member')], help_text='Access level (synced from AllowedEmail)', max_length=1)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='user_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Base User',
                'verbose_name_plural': 'Base Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address that can sign up', max_length=255, unique=True)),
                ('user_type', models.CharField(choices=[('faculty', 'Faculty'), ('staff', 'Staff'), ('officer', 'Officer'), ('club_member', 'Club Member')], help_text='Type of user this email belongs to', max_length=20)),
                ('access_level', models.CharField(choices=[('5', 'Head'), ('4', 'Super Admin'), ('3', 'Course Access'), ('2', 'General User'), ('1', 'Club Member')], default='2', help_text='Access level for this user', max_length=1)),
                ('is_active', models.BooleanField(default=True, help_text='Allow this email to sign up (uncheck to prevent new signups)')),
                ('is_blocked', models.BooleanField(default=False, help_text='Block this user from logging in (blocks existing accounts)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this email was added to allowed list')),
                ('blocked_at', models.DateTimeField(blank=True, help_text='When this email was blocked', null=True)),
                ('block_reason', models.TextField(blank=True, help_text='Reason for blocking (optional)', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Allowed Email',
                'verbose_name_plural': 'Allowed Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('base_user', models.OneToOneField(help_text='Base user account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='club_member_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(help_text='Full name of the club member', max_length=100)),
                ('student_id', models.CharField(help_text='Student ID number', max_length=20, unique=True)),
                ('about', ckeditor.fields.RichTextField(blank=True, help_text='About the club member with rich text', null=True)),
                ('profile_pic', models.ImageField(blank=True, default='defaults/student.png', help_text='Club member profile picture', null=True, upload_to='club_member_photos/')),
                ('last_club_position', models.CharField(blank=True, help_text='Last position held in the club', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Club Member',
                'verbose_name_plural': 'Club Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('base_user', models.OneToOneField(help_text='Base user account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='faculty_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='Name', help_text='Full name of the faculty member', max_length=50)),
                ('shortname', models.CharField(default='N/A', help_text='Short name or initials', max_length=5)),
                ('designation', models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Teaching Assistant', 'Teaching Assistant')], help_text='Academic designation', max_length=20, null=True)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=11)),
                ('bio', models.TextField(help_text='Short biography', max_length=200)),
                ('about', ckeditor.fields.RichTextField(blank=True, help_text='Detailed about section with rich text', null=True)),
                ('profile_pic', models.ImageField(blank=True, default='defaults/faculty.png', help_text='Faculty profile picture', null=True, upload_to='faculty_photos/')),
                ('joining_date', models.DateField(blank=True, help_text='Date when faculty joined', null=True)),
                ('google_scholar_url', models.URLField(blank=True, help_text='Google Scholar profile URL', max_length=255, null=True)),
                ('researchgate_url', models.URLField(blank=True, help_text='ResearchGate profile URL', max_length=255, null=True)),
                ('orcid_url', models.URLField(blank=True, help_text='ORCID profile URL', max_length=255, null=True)),
                ('scopus_url', models.URLField(blank=True, help_text='Scopus profile URL', max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=255, null=True)),
                ('researches', ckeditor.fields.RichTextField(blank=True, help_text='Research information with rich text', null=True)),
                ('citation', models.PositiveIntegerField(blank=True, default=0, help_text='Total citations count', null=True)),
                ('sl', models.PositiveIntegerField(help_text='Serial number for ordering', validators=[django.core.validators.MinValueValidator(1)])),
                ('routine', ckeditor.fields.RichTextField(blank=True, help_text='Faculty routine with rich text', null=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['sl'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('base_user', models.OneToOneField(help_text='Base user account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='officer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(help_text='Full name of the officer', max_length=100)),
                ('position', models.CharField(blank=True, help_text='Official position or title', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=11, null=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography', max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='defaults/officer.png', help_text='Officer profile picture', null=True, upload_to='officer_photos/')),
                ('joining_date', models.DateField(blank=True, help_text='Date when officer joined', null=True)),
                ('sl', models.PositiveIntegerField(help_text='Serial number for ordering', validators=[django.core.validators.MinValueValidator(1)])),
                ('about', ckeditor.fields.RichTextField(blank=True, help_text='Detailed about section with rich text', null=True)),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
                'ordering': ['sl'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('base_user', models.OneToOneField(help_text='Base user account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(help_text='Full name of the staff member', max_length=100)),
                ('designation', models.CharField(choices=[('Lab Assistant', 'Lab Assistant'), ('Lab Attendant', 'Lab Attendant')], help_text='Staff designation', max_length=20)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=11)),
                ('bio', models.TextField(blank=True, help_text='Short biography', max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='defaults/staff.png', help_text='Staff profile picture', null=True, upload_to='staff_photos/')),
                ('joining_date', models.DateField(blank=True, help_text='Date when staff joined', null=True)),
                ('sl', models.PositiveIntegerField(help_text='Serial number for ordering', validators=[django.core.validators.MinValueValidator(1)])),
                ('lab_number', models.CharField(blank=True, help_text='Lab number or identifier', max_length=50, null=True)),
                ('lab_address', models.TextField(blank=True, help_text='Lab address or location', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['sl'],
            },
        ),
        migrations.AddField(
            model_name='baseuser',
            name='allowed_email',
            field=models.ForeignKey(help_text='Reference to the allowed email entry', on_delete=django.db.models.deletion.CASCADE, related_name='base_user', to='people.allowedemail', unique=True),
        ),
    ]
