# Generated by Django 5.2 on 2025-12-08 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='allowed_email',
            field=models.OneToOneField(blank=True, help_text='Reference to the allowed email entry (optional for superusers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_user', to='people.allowedemail'),
        ),
    ]
