# Generated by Django 5.2 on 2025-12-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_baseuser_allowed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='access_level',
            field=models.CharField(blank=True, choices=[('5', 'Head'), ('4', 'Super Admin'), ('3', 'Course Access'), ('2', 'General User'), ('1', 'Club Member')], help_text='Access level (synced from AllowedEmail, optional for superusers)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('faculty', 'Faculty'), ('staff', 'Staff'), ('officer', 'Officer'), ('club_member', 'Club Member')], help_text='Type of user (synced from AllowedEmail, optional for superusers)', max_length=20, null=True),
        ),
    ]
