# Generated by Django 5.2 on 2025-12-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_baseuser_access_level_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography', max_length=200, null=True),
        ),
    ]
