# Generated by Django 5.2 on 2025-12-08 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_faculty_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='sl',
            field=models.PositiveIntegerField(blank=True, help_text='Serial number for ordering', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
