# Generated by Django 5.2 on 2025-12-08 16:44

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_faculty_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_pic', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop image to 1:1 aspect ratio (400x400)', hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=image_cropping.fields.ImageCropField(blank=True, default='defaults/faculty.png', help_text='Faculty profile picture', null=True, upload_to='faculty_photos/'),
        ),
    ]
