# Generated by Django 5.2 on 2025-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_faculty_cropping_alter_faculty_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=11, null=True),
        ),
    ]
