# Generated by Django 5.2 on 2025-12-08 17:31

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_faculty_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=image_cropping.fields.ImageCropField(blank=True, default='defaults/people.png', help_text='Faculty profile picture', null=True, upload_to='faculty_photos/'),
        ),
    ]
