# Generated by Django 5.2 on 2025-12-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_faculty_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaults/people.png', help_text='Staff profile picture', null=True, upload_to='staff_photos/'),
        ),
    ]
