# Generated by Django 5.2 on 2025-12-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_staff_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaults/people.png', help_text='Club member profile picture', null=True, upload_to='club_member_photos/'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaults/people.png', help_text='Officer profile picture', null=True, upload_to='officer_photos/'),
        ),
    ]
