# Generated by Django 5.2 on 2025-12-08 17:33

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_clubmember_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Club member profile picture', null=True, upload_to='club_member_photos/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='Faculty profile picture', null=True, upload_to='faculty_photos/'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Officer profile picture', null=True, upload_to='officer_photos/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Staff profile picture', null=True, upload_to='staff_photos/'),
        ),
    ]
