# Generated by Django 5.2 on 2025-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_alter_clubmember_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=11, null=True),
        ),
    ]
