# Generated by Django 5.2 on 2025-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_alter_staff_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID number', max_length=20, null=True, unique=True),
        ),
    ]
