# Generated by Django 5.2 on 2025-12-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='bio',
            field=models.CharField(blank=True, help_text='Short biography (max 92 characters)', max_length=92, null=True),
        ),
    ]
