# Generated by Django 5.2 on 2025-12-11 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_alter_faculty_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this allowed email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allowed_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
