# Generated by Django 5.2 on 2025-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_allowedemail_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="Unique permission codename (e.g., 'post_notices')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows', null=True)),
                ('category', models.CharField(blank=True, help_text="Permission category (e.g., 'notices', 'clubs', 'academics')", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Permission',
                'verbose_name_plural': 'Custom Permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='allowedemail',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='access_level',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, help_text='Additional permissions directly assigned to this user', related_name='users', to='people.custompermission'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Role name (e.g., 'Content Manager', 'Club Manager')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this role', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active and can be assigned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(help_text='Permissions granted by this role', related_name='roles', to='people.custompermission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='baseuser',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='users', to='people.role'),
        ),
    ]
