# Generated by Django 5.2 on 2025-12-13 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_remove_access_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='custom_permissions',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='allowedemail',
            name='is_power_user',
            field=models.BooleanField(default=False, help_text='Whether this email should create a power user account (can grant permissions)'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_power_user',
            field=models.BooleanField(default=False, help_text='Whether this user can grant permissions to other users'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="Unique permission codename (e.g., 'post_notices')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows', null=True)),
                ('category', models.CharField(blank=True, choices=[('office', 'Office'), ('clubs', 'Clubs'), ('designs', 'Designs'), ('users', 'User Management'), ('academics', 'Academics')], help_text='Permission category for organization', max_length=50, null=True)),
                ('requires_role', models.JSONField(blank=True, default=list, help_text='List of user_types that can have this permission (empty = any role)')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Display priority (lower = more important)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['category', 'priority', 'name'],
                'indexes': [models.Index(fields=['codename'], name='people_perm_codenam_30cfb5_idx'), models.Index(fields=['category', 'is_active'], name='people_perm_categor_ada3df_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='When this permission was granted')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this permission was revoked', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission grant is currently active')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why this permission was granted/revoked', max_length=500, null=True)),
                ('granted_by', models.ForeignKey(help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(help_text='Permission being granted', on_delete=django.db.models.deletion.CASCADE, related_name='user_grants', to='people.permission')),
                ('revoked_by', models.ForeignKey(blank=True, help_text='User who revoked this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_revoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who has this permission', on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.DeleteModel(
            name='CustomPermission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'is_active'], name='people_user_user_id_db1a14_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission', 'is_active'], name='people_user_permiss_ed65b0_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['granted_by', 'granted_at'], name='people_user_granted_76d65e_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'permission'), name='unique_active_user_permission'),
        ),
    ]
