# Generated by Django 5.2 on 2025-12-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_remove_role_permissions_and_more'),
    ]

    operations = [
    ]
