# Generated by Django 5.2 on 2025-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_seed_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.RemoveField(
            model_name='allowedemail',
            name='is_power_user',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_power_user',
        ),
        migrations.AddField(
            model_name='allowedemail',
            name='access_level',
            field=models.CharField(choices=[('5', 'Head'), ('4', 'Super Admin'), ('3', 'Course Access'), ('2', 'General User'), ('1', 'Club Member')], default='2', help_text='Access level for this user', max_length=1),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='access_level',
            field=models.CharField(blank=True, choices=[('5', 'Head'), ('4', 'Super Admin'), ('3', 'Course Access'), ('2', 'General User'), ('1', 'Club Member')], help_text='Access level (synced from AllowedEmail, optional for superusers)', max_length=1, null=True),
        ),
    ]
