# Generated by Django 5.2 on 2025-12-13 17:50

from django.db import migrations, models, connection


def add_cv_if_not_exists(apps, schema_editor):
    """Add cv field only if it doesn't already exist"""
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='people_faculty' AND column_name='cv'
        """)
        exists = cursor.fetchone()
        
        if not exists:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE people_faculty 
                ADD COLUMN cv VARCHAR(100) NULL
            """)


def remove_cv_if_exists(apps, schema_editor):
    """Remove cv field if it exists"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='people_faculty' AND column_name='cv'
        """)
        exists = cursor.fetchone()
        
        if exists:
            cursor.execute("ALTER TABLE people_faculty DROP COLUMN cv")


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_remove_allowedemail_access_level_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_cv_if_not_exists,
            reverse_code=remove_cv_if_exists,
        ),
    ]
