# Generated by Django 5.2 on 2025-12-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_remove_allowedemail_access_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='cv',
            field=models.FileField(blank=True, help_text='Faculty CV/resume document', null=True, upload_to='faculty_cvs/'),
        ),
    ]
