# Generated by Django 5.2 on 2025-12-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_faculty_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_on_study_leave',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this faculty member is currently on study leave', null=True),
        ),
    ]
