# Generated by Django 5.2 on 2025-12-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_faculty_is_on_study_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='last_office_date',
            field=models.DateField(blank=True, help_text='Last date of service at UAP. If set, faculty will be shown in Legacy Faculty section', null=True),
        ),
    ]
