# Generated by Django 5.2 on 2025-12-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_faculty_last_office_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the contributor', max_length=255)),
                ('student_id', models.CharField(blank=True, help_text='Student ID (nullable)', max_length=20, null=True)),
                ('role', models.CharField(help_text="Contributor's role in the project", max_length=255)),
                ('reflection', models.TextField(blank=True, help_text='Optional reflection text from the contributor', null=True)),
                ('portfolio_link', models.URLField(blank=True, help_text='Portfolio or personal website URL', null=True)),
                ('photo', models.ImageField(help_text='Profile photo of the contributor', upload_to='contributor_photos/')),
                ('project_type', models.CharField(choices=[('final', 'Final Development & Deployment'), ('course', 'Course-Based Development')], help_text='Type of project contribution', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for custom sorting within each project_type')),
                ('lines_added', models.PositiveIntegerField(blank=True, help_text='Number of lines added (contribution metric)', null=True)),
                ('lines_deleted', models.PositiveIntegerField(blank=True, help_text='Number of lines deleted (contribution metric)', null=True)),
                ('number_of_commits', models.PositiveIntegerField(blank=True, help_text='Number of commits (contribution metric)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this contributor was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update date')),
            ],
            options={
                'verbose_name': 'Contributor',
                'verbose_name_plural': 'Contributors',
                'ordering': ['project_type', 'order', 'name'],
            },
        ),
    ]
