# Generated by Django 5.2 on 2025-12-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo of the contributor', null=True, upload_to='contributor_photos/'),
        ),
    ]
