# Generated by Django 5.2 on 2025-12-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_alter_contributor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='github_username',
            field=models.CharField(blank=True, help_text='GitHub username (nullable)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID (nullable)', max_length=50, null=True),
        ),
    ]
