# Generated by Django 5.2 on 2025-12-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_contributor_github_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='scholar_data_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time Google Scholar data was fetched', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='scholar_papers',
            field=models.JSONField(blank=True, default=list, help_text='Papers from Google Scholar (stored as JSON). Format: [{"title": "...", "authors": "...", "year": 2024, "citations": 10, "citations_last_year": 5, "url": "...", "venue": "...", "pub_date": "2024-01-15"}]'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='scholar_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Additional Scholar statistics: h-index, i10-index, citation history. Format: {"h_index": 15, "i10_index": 8, "citations_last_year": 25, "papers_last_year": 3, "citation_history": [{"date": "2024-01-01", "citations": 100}, ...]}'),
        ),
    ]
