# Generated by Django 5.2 on 2025-12-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_faculty_scholar_data_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='scholar_data_updated_at',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='scholar_papers',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='scholar_stats',
        ),
    ]
