# Generated by Django 6.0 on 2025-12-24 22:03

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_remove_faculty_scholar_data_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture (Max 600KB, will be compressed and resized to 600x600px if larger)', null=True, upload_to='user_profiles/'),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Club member profile picture (Max 300KB, will be compressed and resized to 400x400px if larger)', null=True, upload_to='club_member_photos/'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo of the contributor (Max 300KB, will be compressed and resized to 400x400px if larger)', null=True, upload_to='contributor_photos/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_pic', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop image to 1:1 aspect ratio (600x600)', hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='cv',
            field=models.FileField(blank=True, help_text='Faculty CV/resume document (PDF only, Max 5MB)', null=True, upload_to='faculty_cvs/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='Faculty profile picture (Max 600KB, will be compressed and resized to 600x600px if larger)', null=True, upload_to='faculty_photos/'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Officer profile picture (Max 300KB, will be compressed and resized to 400x400px if larger)', null=True, upload_to='officer_photos/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Staff profile picture (Max 300KB, will be compressed and resized to 400x400px if larger)', null=True, upload_to='staff_photos/'),
        ),
    ]
