# Generated by Django 5.2 on 2025-12-25 16:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0030_alter_baseuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Publication title', max_length=500)),
                ('pub_year', models.IntegerField(help_text='Publication year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('type', models.CharField(choices=[('journal', 'Journal'), ('conf', 'Conference'), ('bookchapter', 'Book Chapter'), ('other', 'Other')], help_text='Type of publication', max_length=20)),
                ('ranking', models.CharField(choices=[('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4'), ('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('a4', 'A4'), ('not_indexed', 'Not Indexed')], help_text='Journal/Conference ranking', max_length=20)),
                ('link', models.URLField(blank=True, help_text='Link to the publication', null=True)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier (DOI)', max_length=255, null=True)),
                ('published_at', models.CharField(blank=True, help_text='Journal/Conference/Venue name', max_length=255, null=True)),
                ('contribution', models.TextField(blank=True, help_text="Author's contribution to the publication", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this publication was added to the system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this publication was last updated')),
                ('faculty', models.ForeignKey(help_text='Faculty member who authored this publication', on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='people.faculty')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-pub_year', 'title'],
                'indexes': [models.Index(fields=['faculty'], name='people_publ_faculty_9c435f_idx'), models.Index(fields=['pub_year'], name='people_publ_pub_yea_62e9c8_idx'), models.Index(fields=['type'], name='people_publ_type_19dd42_idx'), models.Index(fields=['ranking'], name='people_publ_ranking_d7ceaa_idx'), models.Index(fields=['faculty', 'pub_year'], name='people_publ_faculty_d00610_idx')],
            },
        ),
    ]
