# Generated by Django 5.2 on 2025-12-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_publication'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publication',
            name='people_publ_type_19dd42_idx',
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, choices=[('journal', 'Journal'), ('conf', 'Conference'), ('bookchapter', 'Book Chapter'), ('other', 'Other')], help_text='Type of publication', max_length=20, null=True),
        ),
    ]
