# Generated by Django 5.2 on 2025-12-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_club_cover_photo_alter_club_logo'),
        ('people', '0032_remove_publication_people_publ_type_19dd42_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='club',
            field=models.ForeignKey(blank=True, help_text='The club this email is associated with (for club_member type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_emails', to='clubs.club'),
        ),
    ]
