# Generated by Django 5.2 on 2026-01-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0035_add_faculty_qualification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_inter_department',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this faculty member is from another department (inter-department faculty)', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_visiting',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this faculty member is a visiting faculty', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ranking',
            field=models.CharField(choices=[('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4'), ('a_star', 'A*'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('not_indexed', 'Not Indexed')], help_text='Journal/Conference ranking', max_length=20),
        ),
    ]
