# Generated by Django 5.2 on 2026-01-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_add_inter_department_visiting_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='is_inter_department',
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_inter_departmental',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this faculty member is an inter-departmental faculty', null=True),
        ),
    ]
