# Generated by Django 6.0 on 2026-01-04 11:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_remove_faculty_is_inter_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed about section with rich text', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ranking',
            field=models.CharField(choices=[('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4'), ('a_star', 'A*'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('wos_scopus_indexed', 'WoS/Scopus Indexed'), ('not_indexed', 'Not Indexed')], help_text='Journal/Conference ranking', max_length=20),
        ),
    ]
