# Generated by Django 6.0 on 2026-01-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0038_staff_about_alter_publication_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='about',
        ),
    ]
