# Generated by Django 5.2 on 2025-12-07 20:30

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecard',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '400x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop image to 4:5 aspect ratio (400x500)', hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='featurecardimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '400x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop image to 4:5 aspect ratio (400x500)', hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='featurecard',
            name='picture',
            field=image_cropping.fields.ImageCropField(help_text='Main picture for the card', upload_to='feature_cards/'),
        ),
        migrations.AlterField(
            model_name='featurecardimage',
            name='image',
            field=image_cropping.fields.ImageCropField(help_text='Additional picture for detail view', upload_to='feature_cards/detail/'),
        ),
    ]
