# Generated by Django 5.2 on 2025-12-07 22:03

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_featurecard_cropping_featurecardimage_cropping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecard',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop image to 1:1 aspect ratio (400x400)', hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.DeleteModel(
            name='FeatureCardImage',
        ),
    ]
