# Generated by Django 5.2 on 2025-12-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_alter_featurecard_cropping_delete_featurecardimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(help_text='Serial number for ordering', unique=True)),
                ('title', models.CharField(help_text='Tag title (max 20 characters)', max_length=20)),
            ],
            options={
                'verbose_name': 'Hero Tag',
                'verbose_name_plural': 'Hero Tags',
                'ordering': ['sl'],
            },
        ),
    ]
