# Generated by Django 5.2 on 2025-12-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_add_initial_hero_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='herotags',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this tag on the website'),
        ),
    ]
