# Generated by Django 5.2 on 2025-12-08 21:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_herotags_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(help_text='Serial number for ordering', unique=True)),
                ('title', models.CharField(help_text='Title for the admission element', max_length=200)),
                ('content', ckeditor.fields.RichTextField(help_text='Rich text content for the admission element')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Element',
                'verbose_name_plural': 'Admission Elements',
                'ordering': ['sl'],
            },
        ),
    ]
