# Generated by Django 5.2 on 2025-12-08 21:31

from django.db import migrations

def create_initial_admission_elements(apps, schema_editor):
    AdmissionElement = apps.get_model('designs', 'AdmissionElement')
    
    admission_elements_data = [
        {'sl': 1, 'title': 'Admission Info', 'content': '<p>Admission information content will be added here.</p>'},
        {'sl': 2, 'title': 'Tuition Fees', 'content': '<p>Tuition fees information will be added here.</p>'},
        {'sl': 3, 'title': 'Waiver', 'content': '<p>Waiver information will be added here.</p>'},
        {'sl': 4, 'title': 'Programs', 'content': '<p>Programs information will be added here.</p>'},
        {'sl': 5, 'title': 'BSc in CSE', 'content': '<p>BSc in CSE information will be added here.</p>'},
        {'sl': 6, 'title': 'MCSE', 'content': '<p>MCSE information will be added here.</p>'},
        {'sl': 7, 'title': 'Apply Online', 'content': '<p>Apply online information will be added here.</p>'},
    ]
    
    for element_data in admission_elements_data:
        AdmissionElement.objects.get_or_create(
            sl=element_data['sl'],
            defaults={
                'title': element_data['title'],
                'content': element_data['content']
            }
        )

def remove_initial_admission_elements(apps, schema_editor):
    AdmissionElement = apps.get_model('designs', 'AdmissionElement')
    AdmissionElement.objects.filter(sl__in=[1, 2, 3, 4, 5, 6, 7]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0007_admissionelement'),
    ]

    operations = [
        migrations.RunPython(create_initial_admission_elements, remove_initial_admission_elements),
    ]
