# Generated by Django 5.2 on 2025-12-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_add_initial_admission_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionelement',
            name='curriculum_pdf',
            field=models.FileField(blank=True, help_text='Upload curriculum PDF (for BSc and MCSE programs)', null=True, upload_to='admission/curricula/'),
        ),
    ]
