# Generated by Django 5.2 on 2025-12-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0009_admissionelement_curriculum_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Academic year (e.g., 2024)', unique=True)),
                ('pdf', models.FileField(help_text='PDF file for the academic calendar', upload_to='academic_calendars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Calendar',
                'verbose_name_plural': 'Academic Calendars',
                'ordering': ['-year'],
            },
        ),
    ]
