# Generated by Django 5.2 on 2025-12-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_academiccalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='year',
            field=models.CharField(help_text="Academic year or term (e.g., '2025' or 'Spring 2025')", max_length=100, unique=True),
        ),
        migrations.AlterModelOptions(
            name='academiccalendar',
            options={'ordering': ['-created_at'], 'verbose_name': 'Academic Calendar', 'verbose_name_plural': 'Academic Calendars'},
        ),
    ]
