# Generated by Django 6.0 on 2025-12-24 22:03

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0011_alter_academiccalendar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='pdf',
            field=models.FileField(help_text='PDF file for the academic calendar (Max 5MB)', upload_to='academic_calendars/'),
        ),
        migrations.AlterField(
            model_name='admissionelement',
            name='curriculum_pdf',
            field=models.FileField(blank=True, help_text='Upload curriculum PDF (for BSc and MCSE programs, Max 10MB)', null=True, upload_to='admission/curricula/'),
        ),
        migrations.AlterField(
            model_name='featurecard',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop image to 1:1 aspect ratio (600x600)', hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='featurecard',
            name='picture',
            field=image_cropping.fields.ImageCropField(help_text='Main picture for the card (Max 600KB, will be compressed and resized to 600x600px if larger)', upload_to='feature_cards/'),
        ),
    ]
