# Generated by Django 5.2 on 2025-12-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0012_alter_academiccalendar_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(help_text='Short title for the curriculum (max 50 characters)', max_length=50)),
                ('publishing_year', models.IntegerField(help_text='Year when the curriculum was published')),
                ('version', models.FloatField(help_text='Version number of the curriculum (e.g., 1.0, 2.5)')),
                ('pdf', models.FileField(help_text='PDF file of the curriculum (Max 10MB)', upload_to='curricula/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'ordering': ['-publishing_year', '-version'],
                'unique_together': {('short_title', 'publishing_year', 'version')},
            },
        ),
    ]
