# Generated by Django 5.2 on 2025-12-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0013_add_curricula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curricula',
            options={'ordering': ['program', '-running_since_year', 'running_since_semester', '-version'], 'verbose_name': 'Curriculum', 'verbose_name_plural': 'Curricula'},
        ),
        migrations.AddField(
            model_name='curricula',
            name='program',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='bachelor', help_text='Program type (Bachelor, Master, or PhD)', max_length=20),
        ),
        migrations.AddField(
            model_name='curricula',
            name='running_since_semester',
            field=models.CharField(choices=[('spring', 'Spring'), ('fall', 'Fall')], default='spring', help_text='Semester when this curriculum started running (Spring comes before Fall)', max_length=10),
        ),
        migrations.AddField(
            model_name='curricula',
            name='running_since_year',
            field=models.CharField(default='2024', help_text="Year when this curriculum started running (e.g., '2024')", max_length=10),
        ),
    ]
