# Generated by Django 5.2 on 2025-12-27 21:14

import django.db.models.deletion
from django.db import migrations, models


def migrate_program_data(apps, schema_editor):
    """Migrate program string values to ForeignKey"""
    Curricula = apps.get_model('designs', 'Curricula')
    Program = apps.get_model('academics', 'Program')
    
    # Map old string values to program name patterns
    program_mapping = {
        'bachelor': ['bsc', 'bachelor'],
        'master': ['mcse', 'msc', 'master'],
        'phd': ['phd', 'ph.d'],
    }
    
    # Get all programs
    all_programs = list(Program.objects.all())
    if not all_programs:
        # If no programs exist, we can't migrate
        return
    
    for curriculum in Curricula.objects.all():
        old_value = curriculum.program  # This is still the old CharField
        program = None
        
        # Try to find a matching program by name
        patterns = program_mapping.get(old_value, [])
        for prog in all_programs:
            prog_name_lower = prog.name.lower()
            if any(pattern in prog_name_lower for pattern in patterns):
                program = prog
                break
        
        # If no program found, use first available program
        if not program:
            program = all_programs[0]
        
        # Update the new field
        curriculum.program_new = program
        curriculum.save()


def reverse_migrate_program_data(apps, schema_editor):
    """Reverse migration - convert ForeignKey back to string"""
    # This would require storing the old value, which we don't have
    # So we'll just set a default
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_course_course_outline_pdf'),
        ('designs', '0014_update_curricula_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curricula',
            unique_together=set(),
        ),
        # Add new ForeignKey field as nullable first
        migrations.AddField(
            model_name='curricula',
            name='program_new',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='curricula_new',
                to='academics.program',
            ),
        ),
        # Migrate data from old field to new field
        migrations.RunPython(migrate_program_data, reverse_migrate_program_data),
        # Remove old field
        migrations.RemoveField(
            model_name='curricula',
            name='program',
        ),
        # Rename new field to program
        migrations.RenameField(
            model_name='curricula',
            old_name='program_new',
            new_name='program',
        ),
        # Make it non-nullable
        migrations.AlterField(
            model_name='curricula',
            name='program',
            field=models.ForeignKey(
                help_text='Program this curriculum belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='curricula',
                to='academics.program',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='curricula',
            unique_together={('short_title', 'program', 'publishing_year', 'version', 'running_since_year', 'running_since_semester')},
        ),
    ]
