# Generated by Django 5.2 on 2025-12-09 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Degree Program Name')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='e.g., CSE 2101', max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('credit_hours', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Credit Hours (Cr Hr)')),
                ('contact_hours', models.PositiveSmallIntegerField(verbose_name='Contact Hours')),
                ('course_type', models.CharField(choices=[('TH', 'Theory'), ('LB', 'Lab')], default='TH', help_text='Designates if the course is Theory (TH) or Lab (LB).', max_length=2, verbose_name='Course Type')),
                ('course_outline_pdf', models.FileField(blank=True, help_text='Upload the official PDF document containing the course outline/syllabus.', null=True, upload_to='course_outlines/', verbose_name='Course Outline PDF')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.program')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['program', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., PO1, PO2, PO3', max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='The full statement for the Program Outcome.')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_outcomes', to='academics.program')),
            ],
            options={
                'verbose_name': 'Program Outcome',
                'verbose_name_plural': 'Program Outcomes',
                'ordering': ['program', 'code'],
                'unique_together': {('code', 'program')},
            },
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField(help_text='The unique sequence number (1, 2, 3...) for this CO within the course.', verbose_name='CO Sequence Number')),
                ('statement', models.TextField(verbose_name='Course Outcome Statement')),
                ('blooms_level', models.CharField(choices=[('K1', 'K1: Remember (Knowledge/Cognitive) - Recall facts'), ('K2', 'K2: Understand (Knowledge/Cognitive) - Explain ideas'), ('K3', 'K3: Apply (Knowledge/Cognitive) - Use in new situations'), ('K4', 'K4: Analyze (Knowledge/Cognitive) - Break down/Compare'), ('K5', 'K5: Evaluate (Knowledge/Cognitive) - Judge value/Justify'), ('K6', 'K6: Create (Knowledge/Cognitive) - Produce new work/Design')], help_text='The cognitive level being assessed.', max_length=10)),
                ('knowledge_profile', models.CharField(choices=[('K1', 'K1: Systematic Natural Sciences (Physics, Chemistry, Biology)'), ('K2', 'K2: Conceptually Based Math/Stats (Analytical tools and models)'), ('K3', 'K3: Theory-Based Engineering Fmntls (Core engineering principles)'), ('K4', 'K4: Specialist Knowledge/Forefront (Advanced, niche discipline knowledge)'), ('K5', 'K5: Engineering Design Support (Knowledge for creating solutions)'), ('K6', 'K6: Engineering Practice (Technology) (Application of techniques/tools)'), ('K7', 'K7: Role in Society & Ethics (Impacts, responsibility, safety)'), ('K8', 'K8: Research Literature Engagement (Using published academic research)')], help_text='Select the primary knowledge type addressed.', max_length=10)),
                ('problem_attribute', models.CharField(choices=[('P1', 'P1: In-Depth Knowledge Required (Needs K1-K8 level knowledge)'), ('P2', 'P2: Wide-Ranging/Conflicting Req. (Involves multiple disciplines/issues)'), ('P3', 'P3: No Obvious Solution/Abstract (Requires originality and modeling)'), ('P4', 'P4: Infrequently Encountered Issues (Problems outside routine experience)'), ('P5', 'P5: Outside Standards/Codes (Solution goes beyond standard practices)'), ('P6', 'P6: Diverse Stakeholder Needs (Many groups with varying, complex needs)'), ('P7', 'P7: Many Interdependent Parts (High-level system with sub-problems)')], help_text='Select the attribute that best defines the problem complexity.', max_length=10)),
                ('activity_attribute', models.CharField(blank=True, choices=[('A1', 'A1: Diverse Resource Use (Involves people, money, equipment, etc.)'), ('A2', 'A2: Resolve Significant Conflicts (Managing wide-ranging/conflicting issues)'), ('A3', 'A3: Creative Use of Principles (Applying novel or unconventional methods)'), ('A4', 'A4: Significant Consequences (High risk/difficulty in prediction)'), ('A5', 'A5: Beyond Previous Experience (Applying principles-based, non-routine approaches)')], help_text='Select the characteristic that defines the required engineering activity.', max_length=10, null=True)),
                ('total_assessment_marks', models.PositiveSmallIntegerField(default=0, help_text='Total marks across all assessments used to measure this specific CO.')),
                ('activity', models.CharField(help_text='The primary pedagogical activity type (e.g., Lecture, Laboratory Session, Design Project).', max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='academics.course')),
                ('program_outcome', models.ForeignKey(help_text='A Course Outcome must map to exactly one Program Outcome.', on_delete=django.db.models.deletion.RESTRICT, related_name='contributing_outcomes', to='academics.programoutcome', verbose_name='Mapped Program Outcome')),
            ],
            options={
                'verbose_name': 'Course Outcome',
                'verbose_name_plural': 'Course Outcomes',
                'ordering': ['course', 'sequence_number'],
                'unique_together': {('course', 'sequence_number')},
            },
        ),
    ]
