# Generated by Django 5.2 on 2025-12-09 21:34

from django.db import migrations


def create_baete_program_outcomes(apps, schema_editor):
    """
    Create BAETE Program Outcomes (PO1 through PO12) for the first Program in the database.
    """
    Program = apps.get_model('academics', 'Program')
    ProgramOutcome = apps.get_model('academics', 'ProgramOutcome')
    
    # Get the first program (or create one if none exists)
    program = Program.objects.first()
    if not program:
        program = Program.objects.create(name='BSc in CSE')
    
    # Define BAETE Program Outcomes
    program_outcomes = [
        {
            'code': 'PO1',
            'title': 'Engineering Knowledge',
            'description': 'Apply knowledge of mathematics, natural science, engineering fundamentals and an engineering specialization as specified in K1 to K4 respectively to the solution of complex engineering problems.'
        },
        {
            'code': 'PO2',
            'title': 'Problem Analysis',
            'description': 'Identify, formulate, research literature and analyze complex engineering problems reaching substantiated conclusions using first principles of mathematics, natural sciences and engineering sciences. (K1 to K4)'
        },
        {
            'code': 'PO3',
            'title': 'Design/Development of Solutions',
            'description': 'Design solutions for complex engineering problems and design systems, components or processes that meet specified needs with appropriate consideration for public health and safety, cultural, societal, and environmental considerations. (K5)'
        },
        {
            'code': 'PO4',
            'title': 'Investigation',
            'description': 'Conduct investigations of complex problems using research-based knowledge (K8) and research methods including design of experiments, analysis and interpretation of data, and synthesis of information to provide valid conclusions.'
        },
        {
            'code': 'PO5',
            'title': 'Modern Tool Usage',
            'description': 'Create, select and apply appropriate techniques, resources, and modern engineering and IT tools, including prediction and modelling, to complex engineering problems, with an understanding of the limitations. (K6)'
        },
        {
            'code': 'PO6',
            'title': 'The Engineer and Society',
            'description': 'Apply reasoning informed by contextual knowledge to assess societal, health, safety, legal and cultural issues and the consequent responsibilities relevant to professional engineering practice and solutions to complex engineering problems. (K7)'
        },
        {
            'code': 'PO7',
            'title': 'Environment and Sustainability',
            'description': 'Understand and evaluate the sustainability and impact of professional engineering work in the solution of complex engineering problems in societal and environmental contexts. (K7)'
        },
        {
            'code': 'PO8',
            'title': 'Ethics',
            'description': 'Apply ethical principles and commit to professional ethics and responsibilities and norms of engineering practice. (K7)'
        },
        {
            'code': 'PO9',
            'title': 'Individual and Team Work',
            'description': 'Function effectively as an individual, and as a member or leader in diverse teams and in multi-disciplinary settings.'
        },
        {
            'code': 'PO10',
            'title': 'Communication',
            'description': 'Communicate effectively on complex engineering activities with the engineering community and with society at large, such as being able to comprehend and write effective reports and design documentation, make effective presentations, and give and receive clear instructions.'
        },
        {
            'code': 'PO11',
            'title': 'Project Management and Finance',
            'description': 'Demonstrate knowledge and understanding of engineering management principles and economic decision-making and apply these to one\'s own work, as a member and leader in a team, to manage projects and in multidisciplinary environments.'
        },
        {
            'code': 'PO12',
            'title': 'Life-long Learning',
            'description': 'Recognize the need for, and have the preparation and ability to engage in independent and life-long learning in the broadest context of technological change.'
        },
    ]
    
    # Create Program Outcome objects
    for po_data in program_outcomes:
        ProgramOutcome.objects.get_or_create(
            code=po_data['code'],
            program=program,
            defaults={
                'title': po_data['title'],
                'description': po_data['description']
            }
        )


def reverse_create_baete_program_outcomes(apps, schema_editor):
    """
    Remove BAETE Program Outcomes (PO1 through PO12).
    """
    ProgramOutcome = apps.get_model('academics', 'ProgramOutcome')
    ProgramOutcome.objects.filter(code__startswith='PO').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_baete_program_outcomes, reverse_create_baete_program_outcomes),
    ]
