# Generated by Django 5.2 on 2025-12-09 21:37

from django.db import migrations


def create_dummy_courses(apps, schema_editor):
    """
    Create dummy courses for the first Program in the database.
    """
    Program = apps.get_model('academics', 'Program')
    Course = apps.get_model('academics', 'Course')
    
    # Get the first program
    program = Program.objects.first()
    if not program:
        return  # No program exists, skip
    
    # Define dummy courses (typical CSE curriculum)
    courses = [
        {
            'course_code': 'CSE 1101',
            'title': 'Introduction to Computer Science',
            'credit_hours': 3.0,
            'contact_hours': 3,
            'course_type': 'TH'
        },
        {
            'course_code': 'CSE 1102',
            'title': 'Introduction to Computer Science Lab',
            'credit_hours': 1.5,
            'contact_hours': 3,
            'course_type': 'LB'
        },
        {
            'course_code': 'CSE 2101',
            'title': 'Programming Language I',
            'credit_hours': 3.0,
            'contact_hours': 3,
            'course_type': 'TH'
        },
        {
            'course_code': 'CSE 2102',
            'title': 'Programming Language I Lab',
            'credit_hours': 1.5,
            'contact_hours': 3,
            'course_type': 'LB'
        },
        {
            'course_code': 'CSE 2201',
            'title': 'Data Structures',
            'credit_hours': 3.0,
            'contact_hours': 3,
            'course_type': 'TH'
        },
        {
            'course_code': 'CSE 2202',
            'title': 'Data Structures Lab',
            'credit_hours': 1.5,
            'contact_hours': 3,
            'course_type': 'LB'
        },
        {
            'course_code': 'CSE 3101',
            'title': 'Algorithms',
            'credit_hours': 3.0,
            'contact_hours': 3,
            'course_type': 'TH'
        },
        {
            'course_code': 'CSE 3102',
            'title': 'Algorithms Lab',
            'credit_hours': 1.5,
            'contact_hours': 3,
            'course_type': 'LB'
        },
        {
            'course_code': 'CSE 3201',
            'title': 'Database Systems',
            'credit_hours': 3.0,
            'contact_hours': 3,
            'course_type': 'TH'
        },
        {
            'course_code': 'CSE 3202',
            'title': 'Database Systems Lab',
            'credit_hours': 1.5,
            'contact_hours': 3,
            'course_type': 'LB'
        },
        {
            'course_code': 'CSE 4101',
            'title': 'Software Engineering',
            'credit_hours': 3.0,
            'contact_hours': 3,
            'course_type': 'TH'
        },
        {
            'course_code': 'CSE 4102',
            'title': 'Software Engineering Lab',
            'credit_hours': 1.5,
            'contact_hours': 3,
            'course_type': 'LB'
        },
        {
            'course_code': 'CSE 4201',
            'title': 'Computer Networks',
            'credit_hours': 3.0,
            'contact_hours': 3,
            'course_type': 'TH'
        },
        {
            'course_code': 'CSE 4202',
            'title': 'Computer Networks Lab',
            'credit_hours': 1.5,
            'contact_hours': 3,
            'course_type': 'LB'
        },
        {
            'course_code': 'CSE 4301',
            'title': 'Operating Systems',
            'credit_hours': 3.0,
            'contact_hours': 3,
            'course_type': 'TH'
        },
        {
            'course_code': 'CSE 4302',
            'title': 'Operating Systems Lab',
            'credit_hours': 1.5,
            'contact_hours': 3,
            'course_type': 'LB'
        },
    ]
    
    # Create Course objects (skip if already exists)
    for course_data in courses:
        Course.objects.get_or_create(
            course_code=course_data['course_code'],
            defaults={
                'program': program,
                'title': course_data['title'],
                'credit_hours': course_data['credit_hours'],
                'contact_hours': course_data['contact_hours'],
                'course_type': course_data['course_type'],
                'course_outline_pdf': None  # No PDF for dummy courses
            }
        )


def reverse_create_dummy_courses(apps, schema_editor):
    """
    Remove dummy courses.
    """
    Course = apps.get_model('academics', 'Course')
    Course.objects.filter(course_code__startswith='CSE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_add_baete_program_outcomes'),
    ]

    operations = [
        migrations.RunPython(create_dummy_courses, reverse_create_dummy_courses),
    ]
