# Generated by Django 5.2 on 2025-12-09 21:40

from django.db import migrations


def create_course_outcomes(apps, schema_editor):
    """
    Create Course Outcomes (COs) for all courses - 3-5 COs per course.
    """
    Course = apps.get_model('academics', 'Course')
    ProgramOutcome = apps.get_model('academics', 'ProgramOutcome')
    CourseOutcome = apps.get_model('academics', 'CourseOutcome')
    
    # Get all Program Outcomes
    pos = {po.code: po for po in ProgramOutcome.objects.all()}
    
    # Define Course Outcomes for each course
    # Format: course_code: [list of COs with sequence_number, statement, po_code, blooms, kp, pa, aa, marks, activity]
    course_outcomes_data = {
        'CSE 1101': [  # Introduction to Computer Science
            (1, 'Understand fundamental concepts of computer science and computing systems.', 'PO1', 'K2', 'K3', 'P1', None, 30, 'Lecture'),
            (2, 'Apply basic problem-solving techniques to solve simple computational problems.', 'PO2', 'K3', 'K2', 'P2', 'A1', 25, 'Tutorial'),
            (3, 'Demonstrate understanding of computer hardware and software components.', 'PO1', 'K2', 'K3', 'P1', None, 20, 'Lecture'),
            (4, 'Communicate technical concepts effectively in written and oral form.', 'PO10', 'K2', 'K7', 'P1', None, 25, 'Presentation'),
        ],
        'CSE 1102': [  # Introduction to Computer Science Lab
            (1, 'Use basic computer tools and software applications effectively.', 'PO5', 'K3', 'K6', 'P1', 'A1', 30, 'Laboratory Session'),
            (2, 'Apply problem-solving skills in practical computing scenarios.', 'PO2', 'K3', 'K2', 'P2', 'A1', 35, 'Laboratory Session'),
            (3, 'Work collaboratively in a team to complete computing tasks.', 'PO9', 'K3', 'K6', 'P2', 'A1', 35, 'Group Project'),
        ],
        'CSE 2101': [  # Programming Language I
            (1, 'Understand fundamental programming concepts and syntax.', 'PO1', 'K2', 'K3', 'P1', None, 25, 'Lecture'),
            (2, 'Design and implement algorithms to solve programming problems.', 'PO3', 'K4', 'K5', 'P3', 'A3', 30, 'Assignment'),
            (3, 'Apply programming constructs (variables, loops, conditionals, functions) effectively.', 'PO2', 'K3', 'K3', 'P2', 'A1', 25, 'Tutorial'),
            (4, 'Debug and test programs to ensure correctness and efficiency.', 'PO4', 'K4', 'K6', 'P4', 'A2', 20, 'Laboratory Session'),
        ],
        'CSE 2102': [  # Programming Language I Lab
            (1, 'Write, compile, and execute programs using appropriate development tools.', 'PO5', 'K3', 'K6', 'P1', 'A1', 30, 'Laboratory Session'),
            (2, 'Implement solutions to programming problems using appropriate data structures.', 'PO3', 'K3', 'K3', 'P2', 'A1', 35, 'Laboratory Session'),
            (3, 'Test and validate program correctness through systematic testing approaches.', 'PO4', 'K4', 'K6', 'P3', 'A2', 35, 'Laboratory Session'),
        ],
        'CSE 2201': [  # Data Structures
            (1, 'Understand the properties and applications of fundamental data structures.', 'PO1', 'K2', 'K3', 'P1', None, 25, 'Lecture'),
            (2, 'Analyze time and space complexity of data structure operations.', 'PO2', 'K4', 'K2', 'P2', None, 30, 'Tutorial'),
            (3, 'Design and implement appropriate data structures for given problems.', 'PO3', 'K5', 'K5', 'P3', 'A3', 25, 'Assignment'),
            (4, 'Evaluate and select optimal data structures for specific applications.', 'PO5', 'K5', 'K4', 'P4', 'A2', 20, 'Project'),
        ],
        'CSE 2202': [  # Data Structures Lab
            (1, 'Implement various data structures using programming languages.', 'PO3', 'K3', 'K3', 'P2', 'A1', 35, 'Laboratory Session'),
            (2, 'Apply data structures to solve real-world computational problems.', 'PO2', 'K3', 'K4', 'P3', 'A1', 35, 'Laboratory Session'),
            (3, 'Analyze and compare performance of different data structure implementations.', 'PO4', 'K4', 'K2', 'P4', 'A2', 30, 'Laboratory Session'),
        ],
        'CSE 3101': [  # Algorithms
            (1, 'Understand fundamental algorithmic design paradigms and techniques.', 'PO1', 'K2', 'K3', 'P1', None, 25, 'Lecture'),
            (2, 'Analyze time and space complexity of algorithms using asymptotic notation.', 'PO2', 'K4', 'K2', 'P2', None, 30, 'Tutorial'),
            (3, 'Design efficient algorithms for complex computational problems.', 'PO3', 'K5', 'K5', 'P3', 'A3', 25, 'Assignment'),
            (4, 'Evaluate and compare different algorithmic approaches for problem-solving.', 'PO5', 'K5', 'K4', 'P4', 'A2', 20, 'Project'),
        ],
        'CSE 3102': [  # Algorithms Lab
            (1, 'Implement various algorithmic techniques using programming languages.', 'PO3', 'K3', 'K3', 'P2', 'A1', 35, 'Laboratory Session'),
            (2, 'Apply algorithmic knowledge to solve complex computational problems.', 'PO2', 'K3', 'K4', 'P3', 'A1', 35, 'Laboratory Session'),
            (3, 'Analyze and optimize algorithm performance through empirical testing.', 'PO4', 'K4', 'K2', 'P4', 'A2', 30, 'Laboratory Session'),
        ],
        'CSE 3201': [  # Database Systems
            (1, 'Understand fundamental concepts of database systems and data modeling.', 'PO1', 'K2', 'K3', 'P1', None, 25, 'Lecture'),
            (2, 'Design and normalize database schemas using ER modeling and relational theory.', 'PO3', 'K4', 'K5', 'P3', 'A3', 30, 'Assignment'),
            (3, 'Formulate and execute complex SQL queries for data retrieval and manipulation.', 'PO2', 'K3', 'K3', 'P2', 'A1', 25, 'Tutorial'),
            (4, 'Apply database design principles to ensure data integrity and security.', 'PO6', 'K3', 'K7', 'P5', 'A4', 20, 'Project'),
        ],
        'CSE 3202': [  # Database Systems Lab
            (1, 'Implement database schemas using database management systems.', 'PO3', 'K3', 'K6', 'P2', 'A1', 35, 'Laboratory Session'),
            (2, 'Develop database applications with proper query optimization techniques.', 'PO5', 'K3', 'K6', 'P3', 'A1', 35, 'Laboratory Session'),
            (3, 'Design and implement database security and access control mechanisms.', 'PO8', 'K4', 'K7', 'P5', 'A4', 30, 'Laboratory Session'),
        ],
        'CSE 4101': [  # Software Engineering
            (1, 'Understand software development lifecycle and process models.', 'PO1', 'K2', 'K3', 'P1', None, 20, 'Lecture'),
            (2, 'Apply software engineering principles to design software systems.', 'PO3', 'K4', 'K5', 'P3', 'A3', 25, 'Assignment'),
            (3, 'Analyze software requirements and create comprehensive requirement specifications.', 'PO2', 'K4', 'K4', 'P6', 'A2', 25, 'Project'),
            (4, 'Design and implement software testing strategies and quality assurance methods.', 'PO4', 'K3', 'K6', 'P4', 'A2', 20, 'Tutorial'),
            (5, 'Apply project management principles in software development contexts.', 'PO11', 'K3', 'K7', 'P7', 'A1', 10, 'Project'),
        ],
        'CSE 4102': [  # Software Engineering Lab
            (1, 'Use software engineering tools for project management and version control.', 'PO5', 'K3', 'K6', 'P2', 'A1', 30, 'Laboratory Session'),
            (2, 'Develop software projects following software engineering best practices.', 'PO3', 'K3', 'K5', 'P3', 'A1', 35, 'Group Project'),
            (3, 'Work effectively in teams to develop and deliver software solutions.', 'PO9', 'K3', 'K7', 'P7', 'A1', 35, 'Group Project'),
        ],
        'CSE 4201': [  # Computer Networks
            (1, 'Understand fundamental concepts of computer networks and protocols.', 'PO1', 'K2', 'K3', 'P1', None, 25, 'Lecture'),
            (2, 'Analyze network architectures and protocol layers in detail.', 'PO2', 'K4', 'K3', 'P2', None, 30, 'Tutorial'),
            (3, 'Design network topologies and configurations for given requirements.', 'PO3', 'K4', 'K5', 'P3', 'A3', 25, 'Assignment'),
            (4, 'Apply network security principles and protocols in practical scenarios.', 'PO6', 'K3', 'K7', 'P5', 'A4', 20, 'Project'),
        ],
        'CSE 4202': [  # Computer Networks Lab
            (1, 'Configure and manage network devices and protocols using simulation tools.', 'PO5', 'K3', 'K6', 'P2', 'A1', 35, 'Laboratory Session'),
            (2, 'Implement network protocols and analyze network traffic.', 'PO4', 'K3', 'K6', 'P3', 'A2', 35, 'Laboratory Session'),
            (3, 'Troubleshoot network issues and optimize network performance.', 'PO2', 'K4', 'K6', 'P4', 'A2', 30, 'Laboratory Session'),
        ],
        'CSE 4301': [  # Operating Systems
            (1, 'Understand fundamental concepts of operating systems and system architecture.', 'PO1', 'K2', 'K3', 'P1', None, 25, 'Lecture'),
            (2, 'Analyze process scheduling, memory management, and file system concepts.', 'PO2', 'K4', 'K3', 'P2', None, 30, 'Tutorial'),
            (3, 'Design and implement solutions for operating system problems.', 'PO3', 'K4', 'K5', 'P3', 'A3', 25, 'Assignment'),
            (4, 'Evaluate performance and efficiency of different operating system algorithms.', 'PO5', 'K5', 'K4', 'P4', 'A2', 20, 'Project'),
        ],
        'CSE 4302': [  # Operating Systems Lab
            (1, 'Implement operating system concepts using system programming languages.', 'PO3', 'K3', 'K6', 'P2', 'A1', 35, 'Laboratory Session'),
            (2, 'Analyze and modify system behavior through practical experiments.', 'PO4', 'K4', 'K6', 'P3', 'A2', 35, 'Laboratory Session'),
            (3, 'Apply system administration skills in managing operating system resources.', 'PO5', 'K3', 'K6', 'P4', 'A1', 30, 'Laboratory Session'),
        ],
    }
    
    # Create Course Outcomes
    for course_code, cos in course_outcomes_data.items():
        try:
            course = Course.objects.get(course_code=course_code)
            
            for seq_num, statement, po_code, blooms, kp, pa, aa, marks, activity in cos:
                # Get the Program Outcome
                po = pos.get(po_code)
                if not po:
                    continue  # Skip if PO doesn't exist
                
                # Create Course Outcome
                CourseOutcome.objects.get_or_create(
                    course=course,
                    sequence_number=seq_num,
                    defaults={
                        'statement': statement,
                        'program_outcome': po,
                        'blooms_level': blooms,
                        'knowledge_profile': kp,
                        'problem_attribute': pa,
                        'activity_attribute': aa,
                        'total_assessment_marks': marks,
                        'activity': activity
                    }
                )
        except Course.DoesNotExist:
            continue  # Skip if course doesn't exist


def reverse_create_course_outcomes(apps, schema_editor):
    """
    Remove all Course Outcomes.
    """
    CourseOutcome = apps.get_model('academics', 'CourseOutcome')
    CourseOutcome.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_add_dummy_courses'),
    ]

    operations = [
        migrations.RunPython(create_course_outcomes, reverse_create_course_outcomes),
    ]
