# Generated by Django 5.2 on 2025-12-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_add_course_outcomes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['program', 'year_semester', 'course_code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Select courses that must be completed before taking this course.', related_name='required_for', to='academics.course', verbose_name='Prerequisite Courses'),
        ),
        migrations.AddField(
            model_name='course',
            name='year_semester',
            field=models.CharField(choices=[('1-1', 'Year 1, Semester 1'), ('1-2', 'Year 1, Semester 2'), ('2-1', 'Year 2, Semester 1'), ('2-2', 'Year 2, Semester 2'), ('3-1', 'Year 3, Semester 1'), ('3-2', 'Year 3, Semester 2'), ('4-1', 'Year 4, Semester 1'), ('4-2', 'Year 4, Semester 2')], default='1-1', help_text='The academic year and semester when this course is offered (e.g., 1-1, 2-2).', max_length=3, verbose_name='Year-Semester'),
        ),
    ]
