# Generated by Django 5.2 on 2025-12-09 21:42

from django.db import migrations


def update_courses_with_prerequisites(apps, schema_editor):
    """
    Update existing courses with year_semester and prerequisites.
    """
    Course = apps.get_model('academics', 'Course')
    
    # Define year-semester mapping based on course codes
    # Pattern: First digit indicates year, second digit indicates semester
    year_semester_map = {
        'CSE 1101': '1-1',  # Year 1, Semester 1
        'CSE 1102': '1-1',  # Year 1, Semester 1 (Lab)
        'CSE 2101': '2-1',  # Year 2, Semester 1
        'CSE 2102': '2-1',  # Year 2, Semester 1 (Lab)
        'CSE 2201': '2-2',  # Year 2, Semester 2
        'CSE 2202': '2-2',  # Year 2, Semester 2 (Lab)
        'CSE 3101': '3-1',  # Year 3, Semester 1
        'CSE 3102': '3-1',  # Year 3, Semester 1 (Lab)
        'CSE 3201': '3-2',  # Year 3, Semester 2
        'CSE 3202': '3-2',  # Year 3, Semester 2 (Lab)
        'CSE 4101': '4-1',  # Year 4, Semester 1
        'CSE 4102': '4-1',  # Year 4, Semester 1 (Lab)
        'CSE 4201': '4-2',  # Year 4, Semester 2
        'CSE 4202': '4-2',  # Year 4, Semester 2 (Lab)
        'CSE 4301': '4-1',  # Year 4, Semester 1
        'CSE 4302': '4-1',  # Year 4, Semester 1 (Lab)
    }
    
    # Define prerequisites mapping
    # Format: course_code: [list of prerequisite course codes]
    prerequisites_map = {
        'CSE 1102': ['CSE 1101'],  # Lab requires Theory
        'CSE 2101': ['CSE 1101'],  # Programming I requires Intro to CS
        'CSE 2102': ['CSE 1102', 'CSE 2101'],  # Lab requires both Intro Lab and Programming Theory
        'CSE 2201': ['CSE 2101'],  # Data Structures requires Programming I
        'CSE 2202': ['CSE 2102', 'CSE 2201'],  # Lab requires Programming Lab and Data Structures Theory
        'CSE 3101': ['CSE 2201'],  # Algorithms requires Data Structures
        'CSE 3102': ['CSE 2202', 'CSE 3101'],  # Lab requires Data Structures Lab and Algorithms Theory
        'CSE 3201': ['CSE 2101'],  # Database Systems requires Programming I
        'CSE 3202': ['CSE 2102', 'CSE 3201'],  # Lab requires Programming Lab and Database Theory
        'CSE 4101': ['CSE 3101', 'CSE 3201'],  # Software Engineering requires Algorithms and Database
        'CSE 4102': ['CSE 3102', 'CSE 4101'],  # Lab requires Algorithms Lab and Software Engineering Theory
        'CSE 4201': ['CSE 3101'],  # Computer Networks requires Algorithms
        'CSE 4202': ['CSE 3102', 'CSE 4201'],  # Lab requires Algorithms Lab and Networks Theory
        'CSE 4301': ['CSE 2201', 'CSE 3101'],  # Operating Systems requires Data Structures and Algorithms
        'CSE 4302': ['CSE 2202', 'CSE 4301'],  # Lab requires Data Structures Lab and OS Theory
    }
    
    # Get all courses
    courses_dict = {}
    for course in Course.objects.all():
        courses_dict[course.course_code] = course
    
    # Update year_semester and prerequisites
    for course_code, year_semester in year_semester_map.items():
        if course_code in courses_dict:
            course = courses_dict[course_code]
            course.year_semester = year_semester
            course.save()
    
    # Add prerequisites
    for course_code, prereq_codes in prerequisites_map.items():
        if course_code in courses_dict:
            course = courses_dict[course_code]
            # Clear existing prerequisites
            course.prerequisites.clear()
            # Add new prerequisites
            for prereq_code in prereq_codes:
                if prereq_code in courses_dict:
                    course.prerequisites.add(courses_dict[prereq_code])


def reverse_update_courses_with_prerequisites(apps, schema_editor):
    """
    Reverse: Clear prerequisites and reset year_semester to default.
    """
    Course = apps.get_model('academics', 'Course')
    
    for course in Course.objects.all():
        course.prerequisites.clear()
        course.year_semester = '1-1'
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_course_options_course_prerequisites_and_more'),
    ]

    operations = [
        migrations.RunPython(update_courses_with_prerequisites, reverse_update_courses_with_prerequisites),
    ]
