# Generated by Django 5.2 on 2025-12-09 22:00

from django.db import migrations


def add_theory_course_1_1(apps, schema_editor):
    """
    Add a theory course for Year 1, Semester 1.
    """
    Program = apps.get_model('academics', 'Program')
    Course = apps.get_model('academics', 'Course')
    
    # Get the first program
    program = Program.objects.first()
    if not program:
        return  # No program exists, skip
    
    # Create a new theory course for 1-1
    course, created = Course.objects.get_or_create(
        course_code='CSE 1103',
        defaults={
            'program': program,
            'title': 'Discrete Mathematics',
            'credit_hours': 3.0,
            'contact_hours': 3,
            'course_type': 'TH',
            'year_semester': '1-1',
        }
    )
    
    if created:
        # No prerequisites for a first semester course
        course.prerequisites.clear()


def reverse_add_theory_course_1_1(apps, schema_editor):
    """
    Remove the added theory course.
    """
    Course = apps.get_model('academics', 'Course')
    Course.objects.filter(course_code='CSE 1103').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_update_courses_with_prerequisites'),
    ]

    operations = [
        migrations.RunPython(add_theory_course_1_1, reverse_add_theory_course_1_1),
    ]
