# Generated by Django 5.2 on 2025-12-11 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_add_theory_course_1_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoutcome',
            options={'ordering': ['course', 'sequence_number'], 'verbose_name': 'Course Learning Outcome', 'verbose_name_plural': 'Course Learning Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='programoutcome',
            options={'ordering': ['program', 'code'], 'verbose_name': 'Program Learning Outcome', 'verbose_name_plural': 'Program Learning Outcomes'},
        ),
        migrations.AlterField(
            model_name='courseoutcome',
            name='program_outcome',
            field=models.ForeignKey(help_text='A Course Learning Outcome must map to exactly one Program Learning Outcome.', on_delete=django.db.models.deletion.RESTRICT, related_name='contributing_outcomes', to='academics.programoutcome', verbose_name='Mapped Program Learning Outcome'),
        ),
        migrations.AlterField(
            model_name='courseoutcome',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(help_text='The unique sequence number (1, 2, 3...) for this CLO within the course.', verbose_name='CLO Sequence Number'),
        ),
        migrations.AlterField(
            model_name='courseoutcome',
            name='statement',
            field=models.TextField(verbose_name='Course Learning Outcome Statement'),
        ),
        migrations.AlterField(
            model_name='programoutcome',
            name='code',
            field=models.CharField(help_text='e.g., PLO1, PLO2, PLO3', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='programoutcome',
            name='description',
            field=models.TextField(blank=True, help_text='The full statement for the Program Learning Outcome.'),
        ),
    ]
