# Generated by Django 5.2 on 2025-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_courseoutcome_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutcome',
            name='blooms_level',
            field=models.CharField(choices=[('K1', 'K1: Remember – Recall facts and basic concepts'), ('K2', 'K2: Understand – Explain ideas or concepts'), ('K3', 'K3: Apply – Use information in new situations'), ('K4', 'K4: Analyze – Break information into parts / Compare'), ('K5', 'K5: Evaluate – Justify decisions / Judge value'), ('K6', 'K6: Create – Produce new or original work'), ('A1', 'A1: Receiving – Awareness / Willingness to listen'), ('A2', 'A2: Responding – Participation / Active engagement'), ('A3', 'A3: Valuing – Acceptance of values / Commitment'), ('A4', 'A4: Organizing – Integrating values / Prioritizing'), ('A5', 'A5: Characterizing – Consistent value-driven behavior'), ('P1', 'P1: Imitation – Copying actions / Following demonstration'), ('P2', 'P2: Manipulation – Performing with guidance'), ('P3', 'P3: Precision – Accurate, independent performance'), ('P4', 'P4: Articulation – Coordinated, combined skills'), ('P5', 'P5: Naturalization – Automatic, mastery-level performance')], help_text='The cognitive level being assessed.', max_length=10),
        ),
    ]
