# Generated by Django 6.0 on 2025-12-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_courseoutcome_blooms_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_outline_pdf',
            field=models.FileField(blank=True, help_text='Upload the official PDF document containing the course outline/syllabus (Max 5MB).', null=True, upload_to='course_outlines/', verbose_name='Course Outline PDF'),
        ),
    ]
